"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { api, Property } from "@/lib/api";
import { formatCurrency, formatPct, STRATEGY_CONFIG, scoreColor } from "@/lib/utils";
import ScoreBadge from "@/components/ScoreBadge";
import StrategyBadge from "@/components/StrategyBadge";
import {
  ArrowLeft, Bed, Bath, Square, MapPin, ExternalLink,
  Calendar, FileText, Sparkles, Copy, Mail, Phone, User, Building2
} from "lucide-react";

export default function PropertyDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = Number(params.id);
  const [property, setProperty] = useState<Property | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [analysisLoading, setAnalysisLoading] = useState(false);
  const [analysisError, setAnalysisError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleGenerateAnalysis = async () => {
    setAnalysisLoading(true);
    setAnalysisError(null);
    try {
      const result = await api.generateAnalysis(id);
      setAnalysis(result.analysis);
    } catch {
      setAnalysisError("Failed to generate analysis. Make sure ANTHROPIC_API_KEY is set in your .env file.");
    } finally {
      setAnalysisLoading(false);
    }
  };

  const handleCopy = () => {
    if (!analysis || !property) return;
    const text = `Investment Analysis: ${property.address}, ${property.city}, ${property.state}\n\n${analysis}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmail = () => {
    if (!analysis || !property) return;
    const subject = encodeURIComponent(`Investment Analysis: ${property.address}`);
    const body = encodeURIComponent(`Hi,\n\nHere is the investment analysis for ${property.address}, ${property.city}, ${property.state} (asking ${property.asking_price ? "$" + property.asking_price.toLocaleString() : "N/A"}):\n\n${analysis}\n\nGenerated by Waco Deal Finder`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  useEffect(() => {
    if (!id) return;
    api.getProperty(id)
      .then(setProperty)
      .catch(() => setError("Property not found"))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return <div className="max-w-5xl mx-auto px-4 py-10 text-gray-500">Loading…</div>;
  if (error || !property) return <div className="max-w-5xl mx-auto px-4 py-10 text-red-600">{error || "Not found"}</div>;

  const p = property;
  const s = p.scores;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6">
      {/* Back */}
      <button onClick={() => router.back()} className="flex items-center gap-1 text-sm text-gray-500 hover:text-gray-900 mb-4">
        <ArrowLeft size={16} /> Back to dashboard
      </button>

      {/* Header */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden mb-6">
        {p.photo_url && (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={p.photo_url} alt={p.address} className="w-full h-56 object-cover" />
        )}
        <div className="p-6">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <h1 className="text-2xl font-bold">{p.address}</h1>
              <p className="flex items-center gap-1 text-gray-500 mt-1">
                <MapPin size={14} />
                {p.city}, {p.state} {p.zip_code}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <StrategyBadge strategy={s?.best_strategy} />
              <ScoreBadge score={s?.best_score ?? null} label="overall" />
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-4 mt-4">
            <span className="text-3xl font-bold">{formatCurrency(p.asking_price)}</span>
            {p.zestimate && p.zestimate !== p.asking_price && (
              <span className="text-gray-500 text-sm">
                Zestimate: {formatCurrency(p.zestimate)}
              </span>
            )}
          </div>

          <div className="flex flex-wrap gap-4 mt-3 text-sm text-gray-600">
            {p.beds != null && <span className="flex items-center gap-1"><Bed size={14} />{p.beds} beds</span>}
            {p.baths != null && <span className="flex items-center gap-1"><Bath size={14} />{p.baths} baths</span>}
            {p.sqft != null && <span className="flex items-center gap-1"><Square size={14} />{p.sqft.toLocaleString()} sqft</span>}
            {p.year_built && <span className="flex items-center gap-1"><Calendar size={14} />Built {p.year_built}</span>}
            {p.days_on_market != null && <span>{p.days_on_market} days on market</span>}
            {p.property_type && <span>{p.property_type.replace(/_/g, " ")}</span>}
          </div>

          <div className="flex gap-3 mt-4">
            <Link
              href={`/offers?property_id=${p.id}`}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors"
            >
              <FileText size={15} /> Generate Offer Letter
            </Link>
            {p.listing_url && (
              <a
                href={p.listing_url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-lg text-sm hover:bg-gray-50 transition-colors"
              >
                <ExternalLink size={15} /> View on Zillow
              </a>
            )}
          </div>
        </div>
      </div>

      {/* Score breakdown */}
      {s && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
          <ScoreCard
            title="Wholesale"
            strategy="wholesale"
            score={s.wholesale_score}
            metrics={[
              { label: "Equity %", value: formatPct(s.wholesale_equity_pct) },
              { label: "Max Offer", value: formatCurrency(s.wholesale_max_offer) },
              { label: "Est. Repairs", value: formatCurrency(s.wholesale_est_repairs) },
              { label: "ARV (Zestimate)", value: formatCurrency(p.zestimate) },
            ]}
            note="70% Rule: Max Offer = ARV × 0.70 − Repairs"
          />
          <ScoreCard
            title="Fix & Flip"
            strategy="flip"
            score={s.flip_score}
            metrics={[
              { label: "Est. Profit", value: formatCurrency(s.flip_profit) },
              { label: "Margin %", value: formatPct(s.flip_margin_pct) },
              { label: "Max Offer", value: formatCurrency(s.flip_max_offer) },
              { label: "ARV (Zestimate)", value: formatCurrency(p.zestimate) },
            ]}
            note="Profit = ARV − Asking − Repairs − Selling/Holding costs"
          />
          <ScoreCard
            title="Long-Term Rental"
            strategy="rental"
            score={s.rental_score}
            metrics={[
              { label: "Est. Monthly Rent", value: formatCurrency(s.rental_monthly_rent) },
              { label: "Cap Rate", value: formatPct(s.rental_cap_rate) },
              { label: "Annual Cash Flow", value: formatCurrency(s.rental_annual_cashflow) },
              { label: "Rent/Price Ratio", value: s.rental_monthly_rent && p.asking_price ? formatPct((s.rental_monthly_rent / p.asking_price) * 100) : "N/A" },
            ]}
            note="Cap Rate = NOI / Price (50% expense ratio applied)"
          />
          <ScoreCard
            title="Airbnb / STR"
            strategy="airbnb"
            score={s.airbnb_score}
            metrics={[
              { label: "Est. Nightly Rate", value: formatCurrency(s.airbnb_nightly_rate) },
              { label: "Monthly Revenue", value: formatCurrency(s.airbnb_monthly_revenue) },
              { label: "Gross Annual Yield", value: formatPct(s.airbnb_annual_yield) },
              { label: "Occupancy Est.", value: "55%" },
            ]}
            note="Revenue = Nightly Rate × 30 days × 55% occupancy"
          />
        </div>
      )}

      {/* Agent / seller contact */}
      {(p.agent_name || p.agent_phone || p.agent_email || p.brokerage) && (
        <div className="bg-white rounded-xl border border-gray-200 p-5 mb-6">
          <h3 className="font-semibold mb-3">Agent / Seller Contact</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
            {p.agent_name && (
              <div className="flex items-center gap-2 text-gray-700">
                <User size={15} className="text-gray-400 shrink-0" />
                <span>{p.agent_name}</span>
              </div>
            )}
            {p.brokerage && (
              <div className="flex items-center gap-2 text-gray-700">
                <Building2 size={15} className="text-gray-400 shrink-0" />
                <span>{p.brokerage}</span>
              </div>
            )}
            {p.agent_phone && (
              <a
                href={`tel:${p.agent_phone}`}
                className="flex items-center gap-2 text-blue-600 hover:underline"
              >
                <Phone size={15} className="shrink-0" />
                <span>{p.agent_phone}</span>
              </a>
            )}
            {p.agent_email && (
              <a
                href={`mailto:${p.agent_email}`}
                className="flex items-center gap-2 text-blue-600 hover:underline"
              >
                <Mail size={15} className="shrink-0" />
                <span>{p.agent_email}</span>
              </a>
            )}
          </div>
        </div>
      )}

      {/* AI Analysis */}
      <div className="bg-white rounded-xl border border-gray-200 p-5 mb-6">
        <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
          <div>
            <h3 className="font-semibold flex items-center gap-2">
              <Sparkles size={16} className="text-purple-500" />
              AI Investment Analysis
            </h3>
            <p className="text-xs text-gray-400 mt-0.5">Claude analyzes pros & cons for all 4 strategies</p>
          </div>
          {!analysis && (
            <button
              onClick={handleGenerateAnalysis}
              disabled={analysisLoading}
              className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg text-sm font-medium hover:bg-purple-700 disabled:opacity-60 transition-colors"
            >
              <Sparkles size={14} />
              {analysisLoading ? "Generating…" : "Generate Analysis"}
            </button>
          )}
        </div>

        {analysisError && (
          <div className="rounded-lg bg-red-50 border border-red-200 p-3 text-sm text-red-700">
            {analysisError}
          </div>
        )}

        {analysisLoading && (
          <div className="space-y-2 animate-pulse">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="h-3 bg-gray-100 rounded" style={{ width: `${70 + (i % 3) * 10}%` }} />
            ))}
          </div>
        )}

        {analysis && (
          <>
            <pre className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap font-sans mb-4">
              {analysis}
            </pre>
            <div className="flex gap-2 flex-wrap">
              <button
                onClick={handleCopy}
                className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-lg text-sm hover:bg-gray-50 transition-colors"
              >
                <Copy size={13} />
                {copied ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={handleEmail}
                className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-lg text-sm hover:bg-gray-50 transition-colors"
              >
                <Mail size={13} />
                Email to Boss
              </button>
              <button
                onClick={() => { setAnalysis(null); setAnalysisError(null); }}
                className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-lg text-sm hover:bg-gray-50 transition-colors text-gray-400"
              >
                Regenerate
              </button>
            </div>
          </>
        )}
      </div>

      {/* Description */}
      {p.description && (
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <h3 className="font-semibold mb-2">Listing Description</h3>
          <p className="text-sm text-gray-600 leading-relaxed">{p.description}</p>
        </div>
      )}
    </div>
  );
}

function ScoreCard({
  title, strategy, score, metrics, note,
}: {
  title: string;
  strategy: keyof typeof STRATEGY_CONFIG;
  score: number | null;
  metrics: { label: string; value: string }[];
  note: string;
}) {
  const config = STRATEGY_CONFIG[strategy];
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-5">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="font-semibold text-base">{title}</h3>
          <p className="text-xs text-gray-400 mt-0.5">{config.description}</p>
        </div>
        <div className="flex items-center gap-2">
          <ScoreBadge score={score} />
        </div>
      </div>

      {/* Score bar */}
      <div className="mb-4">
        <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
          <div
            className="h-full rounded-full transition-all"
            style={{
              width: `${((score ?? 0) / 10) * 100}%`,
              backgroundColor: config.mapColor,
            }}
          />
        </div>
        <div className="flex justify-between text-xs text-gray-400 mt-1">
          <span>0</span>
          <span className={scoreColor(score)}>
            {score != null ? `${score.toFixed(1)} / 10` : "Not scored"}
          </span>
          <span>10</span>
        </div>
      </div>

      <dl className="space-y-2">
        {metrics.map(({ label, value }) => (
          <div key={label} className="flex justify-between text-sm">
            <dt className="text-gray-500">{label}</dt>
            <dd className="font-medium">{value}</dd>
          </div>
        ))}
      </dl>

      <p className="text-xs text-gray-400 mt-3 italic">{note}</p>
    </div>
  );
}
